### ISSUE TITLE
When no submissions, it errors out

### ISSUE THREAD

**Issue by rk23** [rk23/whetstone#16]
![screen shot 2016-02-05 at 10 20 02 pm](https://cloud.githubusercontent.com/assets/8933185/12865069/bf16927e-cc56-11e5-9098-e5ba0b3be04e.png)

**Comment by rk23** [comment]
I think this only happens when we run the cron without submitting a goal

**Comment by djpo** [comment]
I've encountered the error a couple times, but can't replicate it now. What do you think the cron is changing? Is it emptying the goal.subs[user._id] array's elements?

I didn't find the answer, but I added a line that should prevent the error:

**controllers/main.js:65**
```javascript
var weeklySubs = goal.subs[user._id][goal.currentWeek] || [];
```

**Comment by rk23** [comment]
I think it might be bad data in the database, that should work though
